//* --------------------------------------------------*\
//    $SELECTORS - CSS selectors ONLY
// -  tag names, #ids, .classnames, [attributes], etc
//* --------------------------------------------------*/

export const SELECTORS = {
  ALL:                            '#all',
  ANCHOR:                         'a',
  ANCHOR_WITH_HREF:               'a[href]',
  API_RESULTS:                    '[data-loadcomponent="APIResults"]',
  BACKGROUND:                     '.background',
  BANNER_TRIGGER:                 '.banner-close',
  BUTTON:                         'button',
  CHECKED:                        ':checked',
  CHECKED_LABEL:                  ':checked + label',
  CHECKBOX:                       'checkbox',
  CHEVRON_STRIPE:                 '.chevron-stripe',
  CLOSE:                          '.close',
  CLOSE_SEARCH:                   '.close-search',
  DATA_BOTTOM:                    'data-bottomposition',
  DATA_HALFWAY:                   'data-halfway',
  DATA_HAS_ANIMATED:              'data-has-animated',
  DATA_LAZY_LOAD:                 'data-lazyload',
  DATA_POSITION:                  'data-position',
  DATA_VISIBLE:                   '[data-visible]',
  DIV:                            'div',
  DROPDOWN:                       '.dropdown',
  DROPDOWN_CONTENT:               '.dropdown__content',
  DROPDOWN_TOGGLE:                '.dropdown__toggle',
  DROPDOWN_TOGGLE_CLICK:          '.dropdown.click',
  DROPDOWN_TOGGLE_HOVER:          '.dropdown.hover',
  EMAIL:                          '.share--email',
  FACEBOOK:                       '.share--fb',
  FEATUREDVIDEO:                  '.featured-video video',
  FILE_INPUT:                     'input[type=file]',
  FILTER:                         '.filter',
  FILTER_CHOICE:                  '.filter-choice',
  FILTER_OPTION:                  '.filter-option',
  FILTER_TRIGGER:                 '.filter-trigger',
  FORM:                           'form',
  FORM_FIELDS:                    'input, select, textarea',
  HTML:                           'html',
  INVALID:                        ':invalid',
  LANDING_PAGE_TITLE:             '.landing-page-header__title',
  LINKEDIN:                       '.share--li',
  LOADING:                        '.loading',
  LOAD_MORE:                      '.load-more',
  NAV:                            '.primary-nav',
  NAV_TRIGGER:                    '.nav-trigger',
  NESTED:                         '.nested',
  OGDESC:                         'meta[property="og:description"]',
  OGTITLE:                        'meta[property="og:title"]',
  OGURL:                          'meta[property="og:url"]',
  OPEN_SEARCH:                    '.open-search',
  OPTGROUP:                       'optgroup',
  PARAGRAPH:                      'p',
  PLAYER:                         '.player',
  PLAY_TRIGGER:                   '.video__play-trigger',
  POST_COUNT:                     '.post-count .count',
  POST_LISTING:                   '.post-listing',
  RESULTS_CONTAINER:              '.results-container',
  SECONDARY_BLOG_LISTING:         '.secondary-blog-listing',
  SEARCH_INPUT:                   '.search-field__input',
  SELECTED:                       '.selected',
  SITE_NAV:                       '.navigation',
  STATISTIC_VALUE:                '.statistic__value',
  SUBMIT:                         '[type="submit"]',
  SVG_BG_CONTAINER:               '.svg-background',
  TAB:                            '[role="tab"]',
  TABPANEL:                       '[role="tabpanel"]',
  TWITTER:                        '.share--tw',
};
